const seed = [
 {id:'registration',title:'Company Registration',icon:'🏛️',summary:'Choose an entity and establish your business correctly.',body:'For most venture-backed startups, a private limited company or C-corporation offers clear ownership, limited liability, and easier fundraising. Confirm founder equity, register the entity, obtain tax IDs, open a business bank account, and maintain a cap table from day one.',tags:['incorporation','equity','legal']},
 {id:'funding',title:'Funding & Fundraising',icon:'💸',summary:'Learn the path from bootstrapping to institutional capital.',body:'Fundraising is a process of matching traction and narrative to the right capital. Start with a concise deck: problem, solution, market, traction, business model, competition, team, financials, and ask. Build investor relationships before you need capital and keep your data room current.',tags:['angels','vc','pitch deck']},
 {id:'compliance',title:'Legal & Compliance',icon:'⚖️',summary:'Protect the business, customers, and intellectual property.',body:'Create a compliance calendar for contracts, privacy, employment, taxes, and statutory filings. Use written founder agreements, IP assignment clauses, clear terms of service, and a privacy policy. Consult a qualified local professional for jurisdiction-specific requirements.',tags:['privacy','contracts','IP']},
 {id:'hiring',title:'Hiring & Team',icon:'🤝',summary:'Build an accountable team without losing speed.',body:'Define outcomes before posting a role. Use structured interviews, reference checks, and scorecards. Early hires should be adaptable, customer-focused, and able to own a broad outcome. Combine fair compensation with transparent equity education.',tags:['recruiting','culture','equity']},
 {id:'brand',title:'Brand & Positioning',icon:'✨',summary:'Create a memorable and differentiated market position.',body:'Positioning names the customer, category, alternative, and distinct value. A useful brand system is consistent: one promise, a clear voice, visual rules, and proof points that show why customers should believe you.',tags:['positioning','identity','messaging']},
 {id:'marketing',title:'Marketing & Growth',icon:'📈',summary:'Find repeatable routes to customers and retention.',body:'Start with a narrow ideal customer profile and test one channel at a time. Instrument the funnel from acquisition through activation, retention, referral, and revenue. Scale only after the unit economics and customer experience are working.',tags:['GTM','acquisition','retention']},
 {id:'tax',title:'Taxation & Finance',icon:'🧾',summary:'Establish financial discipline before it becomes urgent.',body:'Separate personal and company finances, track cash weekly, and use a monthly close. Document every expense and understand indirect tax, payroll tax, income tax, and filing deadlines that apply to your region.',tags:['cash flow','bookkeeping','tax']},
 {id:'ai',title:'AI Tools & Automation',icon:'🤖',summary:'Use AI safely to accelerate research and execution.',body:'Use AI to draft, summarize, analyze, and automate repeatable work—but keep human review for decisions, regulated data, and customer-facing claims. Establish a data policy, evaluate vendors, and measure time saved against quality.',tags:['automation','productivity','RAG']}
];
const resources=[{title:'Founder’s pre-launch checklist',type:'Guide',description:'A practical sequence for company setup, customer discovery, and launch.'},{title:'Investor data room template',type:'Template',description:'Organize diligence documents before investor conversations.'},{title:'Startup metrics glossary',type:'Reference',description:'Plain-language definitions for the numbers investors ask about.'}];
const get=(k,f)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(f)); const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state={page:location.hash.slice(1)||'home',articles:get('sn-articles',seed),resources:get('sn-resources',resources),user:get('sn-user',null),history:get('sn-history',[])};
const nav=[['home','Home'],['topics','Explore Topics'],['search','AI Search'],['resources','Resources'],['about','About'],['contact','Contact']];
function save(){put('sn-articles',state.articles);put('sn-resources',state.resources);put('sn-user',state.user);put('sn-history',state.history)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m){const e=document.querySelector('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function header(){return `<nav class="nav"><div class="shell" style="display:flex;justify-content:space-between;align-items:center;width:100%"><a class="logo" href="#home">Startup <span>Navigator</span></a><div class="links">${nav.map(([id,n])=>`<a class="${state.page===id?'active':''}" href="#${id}">${n}</a>`).join('')}<a href="#${state.user?.role==='admin'?'admin':'login'}" class="button">${state.user?'Dashboard':'Sign in'}</a></div></div></nav>`}
function footer(){return `<footer class="footer"><div class="shell">© 2026 Startup Navigator · Practical guidance, not legal or financial advice.</div></footer>`}
function cards(items=state.articles){return `<div class="grid">${items.map(a=>`<article class="card topic-card" data-topic="${a.id}"><div class="topic-icon">${a.icon||'📚'}</div><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><div class="sources">${(a.tags||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`).join('')}</div>`}
function home(){return `<section class="hero"><div class="shell"><div class="eyebrow">Your founder operating system</div><h1>Navigate every stage of your startup with clarity.</h1><p>Clear, practical guidance on company building—from incorporation and compliance to funding, AI, and durable growth.</p><div class="actions"><a class="button" href="#topics">Explore topics</a><a class="button ghost" href="#search">Ask the AI guide</a></div></div></section><section class="section"><div class="shell"><h2>Everything founders need, in context.</h2><p class="lead">Expert-informed playbooks that keep the next decision simple.</p>${cards(state.articles.slice(0,6))}</div></section>`}
function topics(){return `<main class="shell"><section class="page-head"><div class="eyebrow">Knowledge base</div><h1>Explore startup topics</h1><p>Find a practical starting point for the decisions in front of you.</p></section>${cards()}</main>`}
function answer(q){const words=q.toLowerCase().match(/[a-z]{3,}/g)||[];const matches=state.articles.map(a=>({...a,score:words.reduce((n,w)=>n+((a.title+' '+a.summary+' '+a.body+' '+a.tags.join(' ')).toLowerCase().includes(w)?1:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,3);if(!matches.length)return `I couldn’t find a direct answer in the knowledge base yet. Try terms like “fundraising”, “hiring”, “compliance”, or “marketing”, or contact us for a resource request.`;return `${matches[0].body} ${matches.length>1?'You may also want to review '+matches.slice(1).map(x=>x.title).join(' and ')+'.':''}`}
function search(){return `<main class="shell"><section class="page-head"><div class="eyebrow">AI knowledge assistant</div><h1>Ask a startup question</h1><p>Retrieval-powered answers grounded in the Startup Navigator knowledge base.</p><form class="searchbox" id="ai-form"><input id="question" aria-label="Ask a question" placeholder="e.g. How should I prepare for a seed round?"/><button>Ask AI</button></form><div id="ai-result"></div></section></main>`}
function resourcesPage(){return `<main class="shell"><section class="page-head"><div class="eyebrow">Founder library</div><h1>Resources built for action</h1><p>Reusable tools and reference material for your operating cadence.</p></section><div class="grid">${state.resources.map((r,i)=>`<article class="card resource"><div><span class="tag">${esc(r.type||'Resource')}</span><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p></div><button class="ghost" data-resource="${i}">Save</button></article>`).join('')}</div></main>`}
function about(){return `<main class="shell"><section class="page-head"><div class="eyebrow">Our mission</div><h1>Great startup advice should be easier to use.</h1><p>Startup Navigator turns common founder questions into accessible, structured guidance. It is a starting point for sharper decisions, not a substitute for professional advice.</p></section></main>`}
function contact(){return `<main class="shell"><section class="page-head"><div class="eyebrow">Get in touch</div><h1>How can we help?</h1><p>Tell us which resource or topic would make your founder journey easier.</p></section><section class="card" style="max-width:680px"><form id="contact-form" class="form"><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/><textarea required placeholder="Message"></textarea><button>Send message</button></form></section></main>`}
function login(){return `<main class="shell"><section class="page-head"><div class="eyebrow">Member access</div><h1>Welcome back</h1><p>Use the demo account to explore the admin dashboard.</p></section><section class="card" style="max-width:440px"><form id="login-form" class="form"><input name="email" type="email" placeholder="Email" value="admin@startupnavigator.app" required/><input name="password" type="password" placeholder="Password" value="Navigator2026!" required/><button>Sign in</button></form></section></main>`}
function dashboard(){const queries=state.history.length;return `<main class="shell"><section class="page-head"><div class="eyebrow">${state.user?.role==='admin'?'Admin workspace':'Your activity'}</div><h1>Dashboard</h1><p>Welcome, ${esc(state.user?.name||'Founder')}.</p></section><div class="stats"><div class="stat"><strong>${state.articles.length}</strong><span>Knowledge articles</span></div><div class="stat"><strong>${state.resources.length}</strong><span>Resources</span></div><div class="stat"><strong>${queries}</strong><span>AI searches</span></div></div>${state.user?.role==='admin'?adminPanel():''}<section class="card" style="margin-top:22px"><h3>Recent AI searches</h3>${state.history.length?`<ul class="history">${state.history.slice(0,8).map(h=>`<li><span>${esc(h.q)}</span><small>${new Date(h.at).toLocaleDateString()}</small></li>`).join('')}</ul>`:'<p class="empty">No searches yet. Ask the AI guide to start your history.</p>'}</section></main>`}
function adminPanel(){return `<section class="card" style="margin-top:22px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><h3>Manage knowledge base</h3><p>Articles power the AI search responses.</p></div><button id="new-article">Add article</button></div><div class="history">${state.articles.map(a=>`<div style="padding:12px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:10px"><div><strong>${esc(a.title)}</strong><br><small>${esc(a.summary)}</small></div><div class="admin-actions"><button class="ghost" data-edit="${a.id}">Edit</button><button data-delete="${a.id}">Delete</button></div></div>`).join('')}</div></section>`}
function modal(article){const a=article||{title:'',summary:'',body:'',tags:[]};return `<div class="modal" id="modal"><div class="modal-box"><h2>${article?'Edit':'Add'} article</h2><form class="form" id="article-form"><input name="title" required placeholder="Title" value="${esc(a.title)}"/><input name="summary" required placeholder="Short summary" value="${esc(a.summary)}"/><textarea name="body" required placeholder="Guidance">${esc(a.body)}</textarea><input name="tags" placeholder="Tags, comma separated" value="${esc(a.tags.join(', '))}"/><div class="actions"><button>Save article</button><button type="button" class="ghost" id="close-modal">Cancel</button></div></form></div></div>`}
function render(){state.page=location.hash.slice(1)||'home';const pages={home,topics,search,resources:resourcesPage,about,contact,login,admin:dashboard};let view=(pages[state.page]||home)();document.querySelector('#app').innerHTML=header()+view+footer();bind()}
function bindModal(){document.querySelector('#close-modal')?.addEventListener('click',()=>document.querySelector('#modal')?.remove());document.querySelector('#article-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target), found=state.articles.find(a=>a.title===d.get('title'));const n={id:found?.id||'article-'+Date.now(),icon:found?.icon||'📚',title:d.get('title'),summary:d.get('summary'),body:d.get('body'),tags:d.get('tags').split(',').map(x=>x.trim()).filter(Boolean)};state.articles=found?state.articles.map(a=>a.id===found.id?n:a):[n,...state.articles];save();render();toast('Article saved.');});}
function openModal(article){document.body.insertAdjacentHTML('beforeend',modal(article));bindModal()}
function bind(){document.querySelectorAll('[data-topic]').forEach(e=>e.onclick=()=>{location.hash='search';setTimeout(()=>{const q=document.querySelector('#question');q.value='Tell me about '+e.querySelector('h3').textContent;document.querySelector('#ai-form').requestSubmit()},50)});document.querySelector('#ai-form')?.addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#question').value.trim();if(!q)return toast('Please enter a question.');const result=document.querySelector('#ai-result');result.innerHTML='<p class="lead" style="margin-top:20px">Searching the knowledge base…</p>';setTimeout(()=>{const sources=state.articles.filter(a=>answer(q).includes(a.body)).slice(0,3);state.history.unshift({q,at:Date.now()});save();result.innerHTML=`<div class="answer"><div class="card"><div class="eyebrow">Grounded answer</div><p>${esc(answer(q))}</p><div class="sources">${sources.map(s=>`<span class="tag">${esc(s.title)}</span>`).join('')}</div></div></div>`},450)});document.querySelector('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('Thanks — your message has been received.')});document.querySelector('#login-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);if(d.get('email')==='admin@startupnavigator.app'&&d.get('password')==='Navigator2026!'){state.user={name:'Alex Morgan',role:'admin'};save();location.hash='admin';toast('Signed in successfully.')}else toast('Check your email and password, then try again.')});document.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>toast('Resource saved to your library.'));document.querySelector('#new-article')?.addEventListener('click',()=>openModal());document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(state.articles.find(a=>a.id===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this article?')){state.articles=state.articles.filter(a=>a.id!==b.dataset.delete);save();render();toast('Article deleted.')}});}
window.addEventListener('hashchange',render);render();
